go:
	pdflatex segabs_example.ltx
	bibtex segabs_example
	pdflatex segabs_example.ltx
	pdflatex segabs_example.ltx
	pdflatex segabs_final.ltx

clean:
	rm segabs_example.aux segabs_example.bbl \
	   segabs_example.blg segabs_example.log \
	   segabs_final.aux segabs_final.log
